name: 构建 cfspeed
on:  
  workflow_dispatch:   # 允许手动触发

jobs:
  delete_releases:
    name: 删除旧版本
    runs-on: ubuntu-latest
    steps:
      - name: 删除旧版本
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { owner, repo } = context.repo;
            const releases = await github.rest.repos.listReleases({
              owner,
              repo
            });
            
            for (const release of releases.data) {
              await github.rest.repos.deleteRelease({
                owner,
                repo,
                release_id: release.id
              });
              
              if (release.tag_name) {
                try {
                  await github.rest.git.deleteRef({
                    owner,
                    repo,
                    ref: `tags/${release.tag_name}` 
                  });
                } catch (e) {
                  console.log(`Failed to delete tag ${release.tag_name}: ${e}`);
                }
              }
            }
            
  build_all:
    name: 构建全平台
    runs-on: ubuntu-latest
    needs: delete_releases
    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 设置 Rust 环境
        uses: actions-rust-lang/setup-rust-toolchain@v1.11.0
        with:
          rust-version: '1.82.0'

      - name: 安装 cross
        run: |
          cargo install cross

      - name: 构建 Windows
        run: |
          mkdir -p build/windows
          cross build --release --target x86_64-pc-windows-gnu
          cp target/x86_64-pc-windows-gnu/release/cfspeed.exe build/windows/cfspeed.exe
          tar -czf build/cfspeed_windows_x86_64.tar.gz -C build/windows cfspeed.exe

      - name: 构建 Linux AMD64
        run: |
          mkdir -p build/linux-amd64
          cross build --release --target x86_64-unknown-linux-musl
          cp target/x86_64-unknown-linux-musl/release/cfspeed build/linux-amd64/cfspeed
          tar -czf build/cfspeed_linux_x86_64.tar.gz -C build/linux-amd64 cfspeed

      - name: 构建 Linux ARM64
        run: |
          mkdir -p build/linux-arm64
          cross build --release --target aarch64-unknown-linux-musl
          cp target/aarch64-unknown-linux-musl/release/cfspeed build/linux-arm64/cfspeed
          tar -czf build/cfspeed_linux_aarch64.tar.gz -C build/linux-arm64 cfspeed

      - name: 构建 macOS
        runs-on: macos-latest
        run: |
          mkdir -p build/macos
          cargo build --release
          cp target/release/cfspeed build/macos/cfspeed
          tar -czf build/cfspeed_darwin_x86_64.tar.gz -C build/macos cfspeed

      - name: 提交并推送更改
        if: success()
        run: |
          if [ -d "binaries" ]; then
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
            git pull origin main --no-rebase || git pull origin master --no-rebase
            git add binaries/
            current_time=$(date '+%Y/%m/%d %H:%M:%S')
            if ! git diff --staged --quiet; then
              git commit -m "更新二进制文件 ${current_time}"
              git push
            fi
          fi

      - name: 上传构建产物  
        uses: actions/upload-artifact@v4
        with:  
          name: cfspeed-构建产物  
          path: build/*  

      - name: 创建发布版本  
        uses: softprops/action-gh-release@v2
        if: github.event_name == 'workflow_dispatch'  
        with:  
          tag_name: v${{ github.run_number }}  
          name: Cloudflare CIDR 测速工具 v${{ github.run_number }}  
          draft: false  
          prerelease: false  
          files: |  
            build/*.tar.gz  
            build/sha256sum.txt  
        env:  
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
